services:
  - type: web
    name: namelime-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: doit0abat
        sync: false
      - key: 574812614614553
        sync: false
      - key: rniXO-nQWOpLhsDEQEydU0zDJy4
        sync: false
      - key: pk_test_51SgUpLHg5Yy2uSkfYCfO2hiOPNKjRBhvmOQNJzO0vNgmI5g1SWpNR3LCQyjh9ZzXXertL23Ytmb891GRbA8bGdfV008ubLPv3c
        sync: false
      - key: VITE_APP_URL
        value: https://namelime-app.vercel.app # Placeholder: User will need to update this after frontend deploy
